# -*- coding: utf-8 -*-
"""Animais em Extinção.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ukNaJkYbK472snZloZYwlAPZi6UwiFtt

### <font color =green> 🌼FAUNA EM EXTINÇÃO 🐪
"""

#importando as bibliotecas
!pip install basedosdados
import basedosdados as bd
import pandas as pd
import seaborn as sns

#carregando os dados
df = bd.read_table(dataset_id='br_mma_extincao',
table_id='fauna_ameacada',
billing_project_id="projetofaunaeflora")

df = pd.DataFrame(df)
df.categoria.unique()
df

#substituindo alguns valores
df.replace({'VU':'Vulneravel'},inplace=True)
df.replace({'EN':'Em Perigo'},inplace=True)
df.replace({'CR':'Em Perigo Critico'},inplace=True)
df.replace({'CR (PEX)':'Provavelmente extinta'},inplace=True)
df.replace({'EX':'Extinta na natureza'},inplace=True)
df.replace({'RE':'Regionalmente Extinto'},inplace=True)
df.replace({'EW':'Extinta'},inplace=True)

g = sns.catplot(x='categoria', kind = 'count',data=df, aspect =3, palette="icefire").set(
    title="Contagem de fauna e flora em extinção ")
g.set_xlabels('')
g.set_ylabels('')

#grupos em extinção
grupo = df.grupo.value_counts().to_frame().reset_index()
grupo.columns = ['grupo','total']
grupo

c = sns.catplot(x='grupo',y='total',kind='bar',data=grupo, palette="Spectral", aspect =3).set(
    title="Tipos de grupos em extinção")
c.set_xlabels('')
c.set_ylabels('')

#grafico dos peixes
peixes = df.query('grupo=="peixes"')
peixes_categoria = peixes.categoria.value_counts().to_frame().reset_index()
peixes_categoria.columns = ['categoria','total']
peixes_categoria
px = sns.catplot(x='categoria', y='total',kind='bar',aspect=2,palette='mako', data=peixes_categoria).set(
    title="Status Peixes")
px.set_xlabels('')
px.set_ylabels('')

#grafico dos invertebrados_terrestres
invertebrados_terrestres = df.query('grupo=="invertebrados_terrestres"')
invertebrados_terrestres_categoria = invertebrados_terrestres.categoria.value_counts().to_frame().reset_index()
invertebrados_terrestres_categoria.columns = ['categoria','total']
invertebrados_terrestres_categoria
px = sns.catplot(x='categoria', y='total',kind='bar',aspect=2,palette='dark:salmon_r', data=invertebrados_terrestres_categoria).set(
    title="Status invertebrados_terrestres")
px.set_xlabels('')
px.set_ylabels('')

#grafico das aves
aves = df.query('grupo=="aves"')
aves_categoria = aves.categoria.value_counts().to_frame().reset_index()
aves_categoria.columns = ['categoria','total']
aves_categoria
px = sns.catplot(x='categoria', y='total',kind='bar',aspect=3,palette='bone_r', data=aves_categoria).set(
    title="Status aves")
px.set_xlabels('')
px.set_ylabels('')

#grafico dos mamifero
mamifero = df.query('grupo=="mamifero"')
mamifero_categoria = peixes.categoria.value_counts().to_frame().reset_index()
mamifero_categoria.columns = ['categoria','total']
mamifero_categoria
px = sns.catplot(x='categoria', y='total',kind='bar',aspect=2,palette='YlOrBr', data=mamifero_categoria).set(
    title="Status mamifero")
px.set_xlabels('')
px.set_ylabels('')

#grafico dos invertebrados_aquaticos
invertebrados_aquaticos = df.query('grupo=="invertebrados_aquaticos"')
invertebrados_aquaticos_categoria = invertebrados_aquaticos.categoria.value_counts().to_frame().reset_index()
invertebrados_aquaticos_categoria.columns = ['categoria','total']
invertebrados_aquaticos_categoria
px = sns.catplot(x='categoria', y='total',kind='bar',aspect=2,palette='Blues', data=invertebrados_aquaticos_categoria).set(
    title="Status invertebrados_aquatico")
px.set_xlabels('')
px.set_ylabels('')

#grafico dos repteis
repteis = df.query('grupo=="repteis"')
repteis_categoria = repteis.categoria.value_counts().to_frame().reset_index()
repteis_categoria.columns = ['categoria','total']
repteis_categoria
px = sns.catplot(x='categoria', y='total',kind='bar',aspect=2,palette='viridis', data=repteis_categoria).set(
    title="Status repteis")
px.set_xlabels('')
px.set_ylabels('')

#grafico dos anfibios
anfibios = df.query('grupo=="anfibios"')
anfibios_categoria = anfibios.categoria.value_counts().to_frame().reset_index()
anfibios_categoria.columns = ['categoria','total']
anfibios_categoria
px = sns.catplot(x='categoria', y='total',kind='bar',aspect=2,palette='Greens', data=anfibios_categoria).set(
    title="Status anfibios")
px.set_xlabels('')
px.set_ylabels('')

